pipelines:
  sample-pipeline:
    group: default
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-526cda3:
        git: https://github.com/sreknar/goCD.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - sample-stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          sample-job:
            timeout: 0
            tasks:
            - exec:
                command: dir
                run_if: passed
            - exec:
                arguments:
                - sample pipeline As Code application
                command: echo
                run_if: passed
    parameters:
      env_sample: dummy value
