---
pipelines:
  sample-pipeline:
    group: sample-group
    label: "${COUNT}"
    materials:
     repo: 
       branch: main
       git: "https://github.com/sreknar/goCD.git"       
    stages:
      sample-stage:
        jobs:
          sample-jobs:
            tasks:
              exec:
                command: dir
                run_if : any
                   
                  
